# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Y:\tmp\github\40623147_finalproject\ui\Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(380, 380)
        Dialog.setMinimumSize(QtCore.QSize(380, 380))
        Dialog.setMaximumSize(QtCore.QSize(380, 380))
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.clearMemoryButton = QtWidgets.QPushButton(Dialog)
        self.clearMemoryButton.setMinimumSize(QtCore.QSize(50, 50))
        self.clearMemoryButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearMemoryButton.setFont(font)
        self.clearMemoryButton.setObjectName("clearMemoryButton")
        self.gridLayout.addWidget(self.clearMemoryButton, 2, 0, 1, 1)
        self.eight40623147 = QtWidgets.QPushButton(Dialog)
        self.eight40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.eight40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.eight40623147.setFont(font)
        self.eight40623147.setObjectName("eight40623147")
        self.gridLayout.addWidget(self.eight40623147, 2, 2, 1, 1)
        self.nine40623147 = QtWidgets.QPushButton(Dialog)
        self.nine40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.nine40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nine40623147.setFont(font)
        self.nine40623147.setObjectName("nine40623147")
        self.gridLayout.addWidget(self.nine40623147, 2, 3, 1, 1)
        self.divisionButton = QtWidgets.QPushButton(Dialog)
        self.divisionButton.setMinimumSize(QtCore.QSize(50, 50))
        self.divisionButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.divisionButton.setFont(font)
        self.divisionButton.setObjectName("divisionButton")
        self.gridLayout.addWidget(self.divisionButton, 2, 4, 1, 1)
        self.squareRootButton = QtWidgets.QPushButton(Dialog)
        self.squareRootButton.setMinimumSize(QtCore.QSize(50, 50))
        self.squareRootButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.squareRootButton.setFont(font)
        self.squareRootButton.setObjectName("squareRootButton")
        self.gridLayout.addWidget(self.squareRootButton, 2, 5, 1, 1)
        self.readMemoryButton = QtWidgets.QPushButton(Dialog)
        self.readMemoryButton.setMinimumSize(QtCore.QSize(50, 50))
        self.readMemoryButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.readMemoryButton.setFont(font)
        self.readMemoryButton.setObjectName("readMemoryButton")
        self.gridLayout.addWidget(self.readMemoryButton, 3, 0, 1, 1)
        self.four40623147 = QtWidgets.QPushButton(Dialog)
        self.four40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.four40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.four40623147.setFont(font)
        self.four40623147.setObjectName("four40623147")
        self.gridLayout.addWidget(self.four40623147, 3, 1, 1, 1)
        self.five40623147 = QtWidgets.QPushButton(Dialog)
        self.five40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.five40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.five40623147.setFont(font)
        self.five40623147.setObjectName("five40623147")
        self.gridLayout.addWidget(self.five40623147, 3, 2, 1, 1)
        self.six40623147 = QtWidgets.QPushButton(Dialog)
        self.six40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.six40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.six40623147.setFont(font)
        self.six40623147.setObjectName("six40623147")
        self.gridLayout.addWidget(self.six40623147, 3, 3, 1, 1)
        self.timesButton = QtWidgets.QPushButton(Dialog)
        self.timesButton.setMinimumSize(QtCore.QSize(50, 50))
        self.timesButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.timesButton.setFont(font)
        self.timesButton.setObjectName("timesButton")
        self.gridLayout.addWidget(self.timesButton, 3, 4, 1, 1)
        self.powerButton = QtWidgets.QPushButton(Dialog)
        self.powerButton.setMinimumSize(QtCore.QSize(50, 50))
        self.powerButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.powerButton.setFont(font)
        self.powerButton.setObjectName("powerButton")
        self.gridLayout.addWidget(self.powerButton, 3, 5, 1, 1)
        self.setMemoryButton = QtWidgets.QPushButton(Dialog)
        self.setMemoryButton.setMinimumSize(QtCore.QSize(50, 50))
        self.setMemoryButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.setMemoryButton.setFont(font)
        self.setMemoryButton.setObjectName("setMemoryButton")
        self.gridLayout.addWidget(self.setMemoryButton, 4, 0, 1, 1)
        self.one40623147 = QtWidgets.QPushButton(Dialog)
        self.one40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.one40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.one40623147.setFont(font)
        self.one40623147.setObjectName("one40623147")
        self.gridLayout.addWidget(self.one40623147, 4, 1, 1, 1)
        self.two40623147 = QtWidgets.QPushButton(Dialog)
        self.two40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.two40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.two40623147.setFont(font)
        self.two40623147.setObjectName("two40623147")
        self.gridLayout.addWidget(self.two40623147, 4, 2, 1, 1)
        self.three40623147 = QtWidgets.QPushButton(Dialog)
        self.three40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.three40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.three40623147.setFont(font)
        self.three40623147.setObjectName("three40623147")
        self.gridLayout.addWidget(self.three40623147, 4, 3, 1, 1)
        self.minusButton = QtWidgets.QPushButton(Dialog)
        self.minusButton.setMinimumSize(QtCore.QSize(50, 50))
        self.minusButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.minusButton.setFont(font)
        self.minusButton.setObjectName("minusButton")
        self.gridLayout.addWidget(self.minusButton, 4, 4, 1, 1)
        self.reciprocalButton = QtWidgets.QPushButton(Dialog)
        self.reciprocalButton.setMinimumSize(QtCore.QSize(50, 50))
        self.reciprocalButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reciprocalButton.setFont(font)
        self.reciprocalButton.setObjectName("reciprocalButton")
        self.gridLayout.addWidget(self.reciprocalButton, 4, 5, 1, 1)
        self.addToMemoryButton = QtWidgets.QPushButton(Dialog)
        self.addToMemoryButton.setMinimumSize(QtCore.QSize(50, 50))
        self.addToMemoryButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addToMemoryButton.setFont(font)
        self.addToMemoryButton.setObjectName("addToMemoryButton")
        self.gridLayout.addWidget(self.addToMemoryButton, 5, 0, 1, 1)
        self.zero40623147 = QtWidgets.QPushButton(Dialog)
        self.zero40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.zero40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.zero40623147.setFont(font)
        self.zero40623147.setObjectName("zero40623147")
        self.gridLayout.addWidget(self.zero40623147, 5, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 5, 2, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_20.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 5, 3, 1, 1)
        self.plusButton = QtWidgets.QPushButton(Dialog)
        self.plusButton.setMinimumSize(QtCore.QSize(50, 50))
        self.plusButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plusButton.setFont(font)
        self.plusButton.setObjectName("plusButton")
        self.gridLayout.addWidget(self.plusButton, 5, 4, 1, 1)
        self.equalButton = QtWidgets.QPushButton(Dialog)
        self.equalButton.setMinimumSize(QtCore.QSize(50, 50))
        self.equalButton.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.gridLayout.addWidget(self.equalButton, 5, 5, 1, 1)
        self.display = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.display.setFont(font)
        self.display.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display.setObjectName("display")
        self.gridLayout.addWidget(self.display, 0, 0, 1, 6)
        self.backspaceButton = QtWidgets.QPushButton(Dialog)
        self.backspaceButton.setMinimumSize(QtCore.QSize(0, 50))
        self.backspaceButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.backspaceButton.setFont(font)
        self.backspaceButton.setObjectName("backspaceButton")
        self.gridLayout.addWidget(self.backspaceButton, 1, 0, 1, 2)
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clearButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 2, 1, 2)
        self.clearAllButton = QtWidgets.QPushButton(Dialog)
        self.clearAllButton.setMinimumSize(QtCore.QSize(0, 50))
        self.clearAllButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearAllButton.setFont(font)
        self.clearAllButton.setObjectName("clearAllButton")
        self.gridLayout.addWidget(self.clearAllButton, 1, 4, 1, 2)
        self.seven40623147 = QtWidgets.QPushButton(Dialog)
        self.seven40623147.setMinimumSize(QtCore.QSize(50, 50))
        self.seven40623147.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.seven40623147.setFont(font)
        self.seven40623147.setObjectName("seven40623147")
        self.gridLayout.addWidget(self.seven40623147, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.clearMemoryButton.setText(_translate("Dialog", "MC"))
        self.eight40623147.setText(_translate("Dialog", "8"))
        self.nine40623147.setText(_translate("Dialog", "9"))
        self.divisionButton.setText(_translate("Dialog", "/"))
        self.squareRootButton.setText(_translate("Dialog", "Sqrt"))
        self.readMemoryButton.setText(_translate("Dialog", "MR"))
        self.four40623147.setText(_translate("Dialog", "4"))
        self.five40623147.setText(_translate("Dialog", "5"))
        self.six40623147.setText(_translate("Dialog", "6"))
        self.timesButton.setText(_translate("Dialog", "*"))
        self.powerButton.setText(_translate("Dialog", "X^2"))
        self.setMemoryButton.setText(_translate("Dialog", "MS"))
        self.one40623147.setText(_translate("Dialog", "1"))
        self.two40623147.setText(_translate("Dialog", "2"))
        self.three40623147.setText(_translate("Dialog", "3"))
        self.minusButton.setText(_translate("Dialog", "-"))
        self.reciprocalButton.setText(_translate("Dialog", "1/x"))
        self.addToMemoryButton.setText(_translate("Dialog", "M+"))
        self.zero40623147.setText(_translate("Dialog", "0"))
        self.pushButton_22.setText(_translate("Dialog", "."))
        self.pushButton_20.setText(_translate("Dialog", "+-"))
        self.plusButton.setText(_translate("Dialog", "+"))
        self.equalButton.setText(_translate("Dialog", "="))
        self.backspaceButton.setText(_translate("Dialog", "Backspace"))
        self.clearButton.setText(_translate("Dialog", "Clear"))
        self.clearAllButton.setText(_translate("Dialog", "Clear All"))
        self.seven40623147.setText(_translate("Dialog", "7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

